# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run_desktop_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('index.html', '.'),
        ('webapp', 'webapp'),
        ('agent_server.py', '.'),
        ('backend', 'backend'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.routing',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.middleware',
        'starlette.middleware.cors',
        'blackboxprotobuf',
        'webview',
        'backend',
        'backend.config',
        'backend.core',
        'backend.core.title_cleaner',
        'backend.core.mp4_parser',
        'backend.core.protobuf_decoder',
        'backend.services',
        'backend.services.icloud_scanner',
        'backend.services.cache_manager',
        'backend.services.audio_exporter',
        'backend.api',
        'backend.api.routes',
        'backend.api.server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Goodnotes Agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Goodnotes Agent',
)
app = BUNDLE(
    coll,
    name='Goodnotes Agent.app',
    icon='app_icon.icns',
    bundle_identifier=None,
)
